---
- hosts: all_ceph_nodes
  remote_user: vagrant
  become: yes
  tasks:
    - name: 'pre-emptive host key verification for SSH'
      shell: ssh-keyscan {{ " ".join(groups['all_ceph_nodes']) }} >> /etc/ssh/ssh_known_hosts

# Admin 'root' user tasks
- hosts: admin_node
  remote_user: vagrant
  become: yes
  tasks:
    - name: 'enable https-based apt installs + update cache'
      apt: name=apt-transport-https update_cache=yes
    - name: 'install ntp'
      apt: name=ntp
    - name: 'add ceph apt-key'
      apt_key:
        url: "https://download.ceph.com/keys/release.asc"
        state: present
      #shell: wget -q -O-  | apt-key add -
    - name: 'add ceph apt repo'
      apt_repository:
        repo: deb https://download.ceph.com/debian-jewel/ jessie main
        state: present
    - name: 'install ceph-deploy'
      apt: name=ceph-deploy

# Admin 'vagrant' user tasks - these need SSH agent forwarding
- hosts: admin_node
  remote_user: vagrant
  become: no
  tasks:
    - name: 'initialize ceph cluster'
      command: ceph-deploy new {{ " ".join(groups['all_ceph_nodes']) }}
      args:
        chdir: /vagrant
